// Mock Customers
export const customers = [
  {
    id: 'C001',
    name: 'John Smith',
    address: '123 Main St, Cityville',
    mobileNumber: '555-1234',
    email: 'john.smith@example.com',
    createdAt: new Date('2023-01-15'),
  },
  {
    id: 'C002',
    name: 'Sarah Johnson',
    address: '456 Oak Ave, Townsburg',
    mobileNumber: '555-5678',
    alternateContactNumber: '555-8765',
    email: 'sarah.j@example.com',
    createdAt: new Date('2023-02-20'),
  },
  {
    id: 'C003',
    name: 'Michael Brown',
    address: '789 Pine Rd, Villageton',
    mobileNumber: '555-9012',
    createdAt: new Date('2023-03-10'),
  },
  {
    id: 'C004',
    name: 'Emily Davis',
    address: '101 Cedar Ln, Hamletville',
    mobileNumber: '555-3456',
    email: 'emily.davis@example.com',
    createdAt: new Date('2023-04-05'),
  },
];

// Mock Vehicles
export const vehicles = [
  {
    id: 'V001',
    customerId: 'C001',
    make: 'Toyota',
    model: 'Corolla',
    year: 2018,
    registrationNumber: 'ABC 123',
    engineNumber: 'EN12345678',
    chassisNumber: 'CH87654321',
    lastOdometerReading: 45000,
    createdAt: new Date('2023-01-15'),
  },
  {
    id: 'V002',
    customerId: 'C002',
    make: 'Honda',
    model: 'Civic',
    year: 2020,
    registrationNumber: 'XYZ 789',
    engineNumber: 'EN87654321',
    lastOdometerReading: 15000,
    createdAt: new Date('2023-02-20'),
  },
  {
    id: 'V003',
    customerId: 'C003',
    make: 'Ford',
    model: 'Focus',
    year: 2019,
    registrationNumber: 'DEF 456',
    lastOdometerReading: 30000,
    createdAt: new Date('2023-03-10'),
  },
  {
    id: 'V004',
    customerId: 'C004',
    make: 'Nissan',
    model: 'Altima',
    year: 2021,
    registrationNumber: 'GHI 789',
    engineNumber: 'EN45678901',
    chassisNumber: 'CH10987654',
    lastOdometerReading: 8000,
    createdAt: new Date('2023-04-05'),
  },
];

// Mock Job Cards
export const jobCards = [
  {
    id: 'JC-23045',
    customerId: 'C001',
    vehicleId: 'V001',
    customerName: 'John Smith',
    vehicleMake: 'Toyota',
    vehicleModel: 'Corolla',
    vehicleReg: 'ABC 123',
    dateOfService: new Date(),
    estimatedCompletionDate: new Date(Date.now() + 86400000), // +1 day
    assignedMechanicId: 'M001',
    odometerReadingAtService: 45000,
    fuelLevel: 'half',
    status: 'in-progress',
    createdAt: new Date(),
    updatedAt: new Date(),
    totalAmount: 250,
    paymentStatus: 'unpaid',
    services: [],
  },
  {
    id: 'JC-23044',
    customerId: 'C002',
    vehicleId: 'V002',
    customerName: 'Sarah Johnson',
    vehicleMake: 'Honda',
    vehicleModel: 'Civic',
    vehicleReg: 'XYZ 789',
    dateOfService: new Date(Date.now() - 86400000), // -1 day
    odometerReadingAtService: 15000,
    fuelLevel: 'full',
    status: 'completed',
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(),
    totalAmount: 180,
    paymentStatus: 'paid',
    services: [],
  },
  {
    id: 'JC-23043',
    customerId: 'C003',
    vehicleId: 'V003',
    customerName: 'Michael Brown',
    vehicleMake: 'Ford',
    vehicleModel: 'Focus',
    vehicleReg: 'DEF 456',
    dateOfService: new Date(Date.now() - 172800000), // -2 days
    odometerReadingAtService: 30000,
    fuelLevel: 'quarter',
    status: 'awaiting-payment',
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(),
    totalAmount: 350,
    paymentStatus: 'unpaid',
    services: [],
  },
  {
    id: 'JC-23042',
    customerId: 'C004',
    vehicleId: 'V004',
    customerName: 'Emily Davis',
    vehicleMake: 'Nissan',
    vehicleModel: 'Altima',
    vehicleReg: 'GHI 789',
    dateOfService: new Date(Date.now() - 259200000), // -3 days
    estimatedCompletionDate: new Date(Date.now() - 172800000),
    odometerReadingAtService: 8000,
    fuelLevel: 'three-quarter',
    status: 'pending',
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(Date.now() - 259200000),
    totalAmount: 120,
    paymentStatus: 'unpaid',
    services: [],
  },
];

// Mock Inventory Items
export const inventoryItems = [
  {
    id: 'P001',
    partName: 'Oil Filter',
    partNumber: 'OF-12345',
    category: 'Engine',
    stockQuantity: 25,
    lowStockThreshold: 5,
    purchasePrice: 8,
    sellingPrice: 15,
    supplierInfo: 'AutoParts Inc.',
  },
  {
    id: 'P002',
    partName: 'Air Filter',
    partNumber: 'AF-67890',
    category: 'Engine',
    stockQuantity: 18,
    lowStockThreshold: 5,
    purchasePrice: 12,
    sellingPrice: 25,
    supplierInfo: 'AutoParts Inc.',
  },
  {
    id: 'P003',
    partName: 'Brake Pads (Front)',
    partNumber: 'BP-F-54321',
    category: 'Brakes',
    stockQuantity: 8,
    lowStockThreshold: 4,
    purchasePrice: 35,
    sellingPrice: 70,
    supplierInfo: 'BrakeMasters Co.',
  },
  {
    id: 'P004',
    partName: 'Brake Pads (Rear)',
    partNumber: 'BP-R-54321',
    category: 'Brakes',
    stockQuantity: 3,
    lowStockThreshold: 4,
    purchasePrice: 30,
    sellingPrice: 65,
    supplierInfo: 'BrakeMasters Co.',
  },
  {
    id: 'P005',
    partName: 'Engine Oil (1L)',
    partNumber: 'EO-5W30-1L',
    category: 'Fluids',
    stockQuantity: 50,
    lowStockThreshold: 10,
    purchasePrice: 5,
    sellingPrice: 12,
    supplierInfo: 'LubriTech',
  },
  {
    id: 'P006',
    partName: 'Windshield Wiper (Pair)',
    partNumber: 'WW-STD-18',
    category: 'Exterior',
    stockQuantity: 15,
    lowStockThreshold: 5,
    purchasePrice: 10,
    sellingPrice: 22,
    supplierInfo: 'VisioWipe Ltd.',
  },
  {
    id: 'P007',
    partName: 'Spark Plugs (Set of 4)',
    partNumber: 'SP-IRID-4',
    category: 'Engine',
    stockQuantity: 12,
    lowStockThreshold: 3,
    purchasePrice: 20,
    sellingPrice: 45,
    supplierInfo: 'SparkTech',
  },
];

// Mock Mechanics
export const mechanics = [
  {
    id: 'M001',
    name: 'David Wilson',
    expertise: ['Engine', 'Electrical'],
    contactNumber: '555-1111',
    activeJobCards: 3,
  },
  {
    id: 'M002',
    name: 'Robert Chen',
    expertise: ['Brakes', 'Suspension'],
    contactNumber: '555-2222',
    activeJobCards: 2,
  },
  {
    id: 'M003',
    name: 'Lisa Patel',
    expertise: ['Diagnostics', 'Electrical'],
    contactNumber: '555-3333',
    activeJobCards: 1,
  },
  {
    id: 'M004',
    name: 'James Rodriguez',
    expertise: ['Engine', 'Transmission'],
    contactNumber: '555-4444',
    activeJobCards: 0,
  },
];

// Mock Predefined Services
export const predefinedServices = [
  {
    id: 'S001',
    serviceName: 'Oil Change',
    defaultDescription: 'Change engine oil and replace oil filter',
    defaultParts: [
      { partId: 'P001', quantity: 1 },
      { partId: 'P005', quantity: 4 },
    ],
    defaultLaborHours: 0.5,
    category: 'Maintenance',
  },
  {
    id: 'S002',
    serviceName: 'Brake Pad Replacement (Front)',
    defaultDescription: 'Replace front brake pads and inspect rotors',
    defaultParts: [{ partId: 'P003', quantity: 1 }],
    defaultLaborHours: 1.5,
    category: 'Brakes',
  },
  {
    id: 'S003',
    serviceName: 'Brake Pad Replacement (Rear)',
    defaultDescription: 'Replace rear brake pads and inspect rotors',
    defaultParts: [{ partId: 'P004', quantity: 1 }],
    defaultLaborHours: 1.5,
    category: 'Brakes',
  },
  {
    id: 'S004',
    serviceName: 'Air Filter Replacement',
    defaultDescription: 'Replace engine air filter',
    defaultParts: [{ partId: 'P002', quantity: 1 }],
    defaultLaborHours: 0.3,
    category: 'Maintenance',
  },
  {
    id: 'S005',
    serviceName: 'Spark Plug Replacement',
    defaultDescription: 'Replace spark plugs',
    defaultParts: [{ partId: 'P007', quantity: 1 }],
    defaultLaborHours: 1.0,
    category: 'Engine',
  },
  {
    id: 'S006',
    serviceName: 'Windshield Wiper Replacement',
    defaultDescription: 'Replace front windshield wipers',
    defaultParts: [{ partId: 'P006', quantity: 1 }],
    defaultLaborHours: 0.2,
    category: 'Exterior',
  },
];
