// Sample predefined services data
export const predefinedServicesData = [
  {
    id: 'service-1',
    name: 'Engine Oil Change',
    description: 'Complete engine oil change with filter replacement',
    price: 650,
    estimatedTime: '30 min',
    category: 'Maintenance',
  },
  {
    id: 'service-2',
    name: 'Air Filter Replacement',
    description: 'Replace air filter to improve engine performance',
    price: 350,
    estimatedTime: '15 min',
    category: 'Maintenance',
  },
  {
    id: 'service-3',
    name: 'Spark Plug Replacement',
    description: 'Replace spark plugs for better ignition',
    price: 400,
    estimatedTime: '30 min',
    category: 'Maintenance',
  },
  {
    id: 'service-4',
    name: 'Chain Lubrication',
    description: 'Clean and lubricate chain for smooth operation',
    price: 250,
    estimatedTime: '15 min',
    category: 'Maintenance',
  },
  {
    id: 'service-5',
    name: 'Brake Pad Replacement',
    description: 'Replace worn out brake pads',
    price: 800,
    estimatedTime: '45 min',
    category: 'Repair',
  },
  {
    id: 'service-6',
    name: 'Wheel Alignment',
    description: 'Adjust wheels for proper alignment',
    price: 500,
    estimatedTime: '30 min',
    category: 'Maintenance',
  },
  {
    id: 'service-7',
    name: 'Carburetor Cleaning',
    description: 'Clean carburetor for better fuel efficiency',
    price: 700,
    estimatedTime: '60 min',
    category: 'Repair',
  },
  {
    id: 'service-8',
    name: 'Full Bike Service',
    description: 'Complete service including oil change, filter replacement, chain lubrication',
    price: 1800,
    estimatedTime: '120 min',
    category: 'Complete Service',
  },
  {
    id: 'service-9',
    name: 'Clutch Adjustment',
    description: 'Adjust clutch for smooth gear shifting',
    price: 350,
    estimatedTime: '30 min',
    category: 'Maintenance',
  },
  {
    id: 'service-10',
    name: 'Fork Oil Replacement',
    description: 'Replace fork oil for better suspension',
    price: 900,
    estimatedTime: '60 min',
    category: 'Maintenance',
  },
  {
    id: 'service-11',
    name: 'Throttle Body Cleaning',
    description: 'Clean throttle body for better performance',
    price: 550,
    estimatedTime: '45 min',
    category: 'Advanced Maintenance',
  },
  {
    id: 'service-12',
    name: 'ECU Reflashing',
    description: 'Reprogram the ECU for better performance',
    price: 2500,
    estimatedTime: '60 min',
    category: 'Advanced Maintenance',
  },
];
